
campaigns:
  description: >
    Iterate through the {accounts list}, and for each {account} use the {account id} to get the campaigns.
  expected_output: >
    A list of campaign ids for the account.
  agent: campaign_manager
  

create_impressions_report:
  description: >
    Use the {campaign ids} to create a report.
  expected_output: >
    A report creation object in JSON.
  agent: campaign_reporter
  context:
    - campaigns

check_report_status:
  description: >
    Check the status of the report using {report id}.
  expected_output: >
    The status of the report.
  agent: campaign_reporter
  context:
    - create_impressions_report

download_report:
  description: >
    Download the report  using {report id}.
  expected_output: >
    The report as JSON.
  agent: campaign_reporter
  context:
    - create_impressions_report