accounts:
  description: >
    Retrieve a list of accounts available to this user.
  expected_output: >
    A list of accounts available to this user.
  agent: account_manager

campaigns:
  description: >
    Iterate through the {accounts list}, and for each {account} use the {account id} to get the campaigns.
  expected_output: >
    A list of campaign ids for the account.
  agent: campaign_manager
  context:
    - accounts

create_impressions_report:
  description: >
    Iterate through the {accounts list}, and for each {account} use the {account id} to get the campaigns.
  expected_output: >
    A list of campaigns for the account formatted as a table in Markdown.
  agent: campaign_reporter
  context:
    - campaigns

check_report_status:
  description: >
    Check the status of the report using {report id}.
  expected_output: >
    The status of the report.
  agent: campaign_reporter
  context:
    - create_impressions_report

download_report:
  description: >
    Download the report  using {report id}.
  expected_output: >
    The report as JSON.
  agent: campaign_reporter
  context:
    - create_impressions_report