list_my_accounts_task:
  description: >
    List all the Retail Media accounts accessible to the account manager.

  expected_output: >
    A formatted list of accounts accessible to the account manager, including all relevant details.

list_brands_for_an_account_task:
  description: >
    List all the Retail Media brands accessible for an account.
    Use the {accountId} to get the account details.

  expected_output: >
    A formatted list of brands accessible to an account, including all relevant details.



