


fetch_campaigns_task:
  description: >
    Get a collection campaigns for account {account_id}.
    Use the pageIndex and pageSize parameters to get all campaigns for the account.
    Do not make more API calls than necessary.
    Reformat each campaign by removing the 'type' field, remap the fields 'name', 'budget' and 'budgetSpent' in 'attributes' to the root level, then remove the 'attributes' field.
    If the budget is not provided, set it to 0.
  expected_output: >
    A collection of campaigns for the account formatted as JSON.



fetch_auction_lineitems:
  description: >
    for each element in the campaigns collection, fetch the auction lineitems using the campaign id.
    If there total items across all pages is zero simply provide an empty list.
    Use the pageIndex and pageSize parameters to get all lineitems for the campaign.
    Do not make more API calls than necessary.
    Reformat each lineitem by removing the 'type' field and remap the fields 'startDate', 'name', 'budget' to the root level, then delete the 'attributes' field.
    If the budget is not provided, set it to 0.
  expected_output: A collection of auction lineitems formatted as JSON.

# preferred_lineitems:
#   description: >
#     Interate through the cached campaigns and for each campaign use the campaigh {id} to get the preferred lineitems.
#     If there total items across all pages is zero simply provide an empty list.
#     Use the pageIndex and pageSize parameters to get all lineitems for the campaign.
#     Do not make more API calls than necessary.
#     Write a file contaning the list of preferred lineitems in JSON format, the directory is 'output', 
#     the file name is '{campaign name}_preferred_lineitems.json' and
#     the content is the list of preferred linitems formated in JSON.
#   expected_output: >
#    A list of preferred lineitems formatted in JSON.
#   agent: lineitems_manager
#   context:
#     - campaigns

sumarise_monthly_lineitem_budget:
  description: >
    Summarize the detailed data from the second API into a meaningful format.
  expected_output: >
    A summary of the data collected from the APIs.
    
lineitems_budget_chart:
  description: >
    Create a bar chart from the summarized lineitem data.
  expected_output: >
    A bar chart image.
