fetch_campaigns_task:
  description: >
    Get a collection campaigns for account {account_id}.
    Use the pageIndex and pageSize parameters to get all campaigns for the account.
    If the budget is not provided  or is zero, ignore the campaign.
    Use the pageIndex and pageSize parameters to get all lineitems for the campaign.
    Do not make more API calls than necessary.
    Reformat each campaign by removing the 'type' field, remap the fields 'name', 'budget' and 'budgetSpent' in 'attributes' to the root level, then remove the 'attributes' field.
    If the budget is not provided, set it to 0.
  expected_output: >
    A collection of campaigns for the account formatted as JSON.

campaigns_budget_pie_chart:
  description: >
    Create a pie chart from the data in the campaigns collection.
    The 'values' should be the sum of the 'budget' field for each campaign.
    The 'labels' should be the 'name' field for each campaign.
    The 'title' should be 'Campaign Budgets'.
    The 'file_name' should be 'output/campaign_budget_pie_chart.png'.
  expected_output: >
    A pie chart image.
