fetch_campaigns_task:
  description: >
    Get the first 100 campaigns for account {account_id} using the Campaigns List Tool.
    Start with page 0 and page size 100.
    Remember the results as [CampaignsList] in the cache.
    If the budget field is null, set it to 0.0,
  expected_output: >
    A list of campaigns remembered as [CampaignList].

campaigns_budget_pie_chart:
  description: >
    Create a pie chart from the data in the [CampaignList].
    The 'labels' should be the 'name' field for each campaign.
    The 'title' should be 'Campaign Budgets for Account {account_id}'.
    The 'file_name' should be 'campaign_budget_pie_chart.png'.
    The 'path' should be 'output'.
  expected_output: >
    A pie chart image file_name.

campaigns_report:
  description: >
    Create a report in Markdown format, with the data from the [CampaignList].
    The report should show a table with the campaign name, start date, status, budget, and budgetSpent.
    The report should include a pie chart of the campaign budgets. Use only the file name of the pie chart, do not include the path.
    The 'title' should be Campaign Budget Report for Account {account_id}.
    do not use "```markdown" or "```" in the markdown file.
  expected_output: >
    A markdown file with the report.
