fetch_campaigns_task:
  description: >
    Get the first 100 campaigns for account {account_id} using the Campaigns List Tool and with_budget is true.
    Remember the results as CampaignsList in the cache.
  expected_output: >
    CampaignList

campaigns_budget_pie_chart:
  description: >
    Create a pie chart from the data in the CampaignList.
    The 'labels' should be the 'name' field for each campaign.
    The 'title' should be 'Campaign Budgets for Account {account_id}'.
    The 'file_name' should be 'campaign_budget_pie_chart.png'.
    The 'path' should be 'output'.
  expected_output: >
    A pie chart image file_name.

campaigns_report:
  description: >
    Create a report in Markdown format, with the data from the [CampaignList].
    Describe the results of the campaign list. 
    The report should show a table with the campaign name, start date, status, budget, and budgetSpent.
    The report should include a pie chart of the campaign budgets. Use only the file name of the pie chart, do not include the path.
    The 'title' should be Campaign Budget Report for Account {account_id}.
    Include a total budget and total budget spent at the end of the report.
    Include a summary of the report at the end.
    do not use "```markdown" or "```" in the markdown file.

  expected_output: >
    A markdown file with the report.
