accounts:
  description: >
    Retrieve a list of accounts available to this user.
  expected_output: >
    A list of accounts available to this user.
  agent: account_manager

campaigns:
  description: >
    Iterate through the {accounts list}, and for each {account} use the {account id} to get the campaigns.
  expected_output: >
    A list of campaigns for the account formatted as a table in Markdown.
  agent: campaign_manager
  context:
    - accounts

auction_lineitems:
  description: >
    Iterate through the {campaigns list}, and for each {campaign} use the {campaign id} to get the lineitems.
  expected_output: >
    A list of auction lineitems for the campaign formatted as a table in Markdown.
  agent: campaign_manager
  context:
    - campaigns

preferred_lineitems:
  description: >
    Iterate through the {campaigns list}, and for each {campaign} use the {campaign id} to get the lineitems.
  expected_output: >
    A list of preferred lineitems for the campaign formatted as a table in Markdown.
  agent: campaign_manager
  context:
    - campaigns
