accounts:
  description: >
    Retrieve a list of accounts available to this user.
  expected_output: >
    A list of accounts available to this user formatted as a table in Markdown.
  agent: account_manager

brands:
  description: >
    Iterate through the {accounts list}, and for each {account} retrieve the Retail Media brands. Use the {account id} to get the brands.
  expected_output: >
    A list of brands for the account formatted as a table in Markdown.
  agent: account_manager
  context:
    - accounts

retailers:
  description: >
    Iterate through the {accounts list}, and for each {account} retrieve the Retail Media retailers. Use the {account id} to get the retailers.
  expected_output: >
    A list of retailers for the account formatted as a table in Markdown.
  agent: account_manager
  context:
    - accounts

analytics:
  description: >
    Analyze the brands and retailers for each account. 
    Count the number of brands.
    Count the number of retailers.

  expected_output: >
    A list of analytics for each account formatted as a table in Markdown.
  agent: account_manager
  context:
    - accounts
    - brands
    - retailers
