account:
  description: >
    Use the account number of {account_id} to get the account details.
  expected_output: >
    A JSON object with the account details.

campaigns:
  description: >
    Use the account number of {account_id} to get a list of campaigns.

  expected_output: >
    A list of campaign ids for the account as a JSON array. Do not include the whold campaign object. Only the campaign Id.

research_demographics:
  description: >
    Use the {artist_name} to get the demographics for the artist.
    You will need to use the Web and Social media to obtain your data.

  expected_output: >
    A JSON object with the social media demographics for the artist.

find_concert_venues:
  description: >
    Use the {artist_name} to find the concerts and venues for {year}, indluding international venues.
    Include the seating capacity of each venue.
    Include the data of each concert.
    You will need to use the Web and Social media to obtain your data.

  expected_output: >
    A JSON array of concerts, dates, venues and their searing capacity for the artist.

formulate_budget:
  description: >
    Formulate an advertising budget for an online advertising campaign using the {artist_name}, the location of the venues and their seating capacity.
    Provide a total budget for the advertising campaign.
    For each concert, formulate a budget amount based on the venue and geographic location. These values should be based on the seating capacity of the venue and the location of the venue.
    Express the budget in USD.
    Ask the human if they would like to proceed with the budget.

  expected_output: >
    A JSON object with the budget for the campaign.

create_campaign:
  description: >
    Use Retail Media API to create the campaign with:
     The {artist_name}, the budget to create a campaign.
     The campaign name is the {artist_name}, the {year}, the date of the first concert and the date of the last concert.
     
     The start date of the campaign should be 60 days before the first concert.
     The end date of the campaign should be the date of the last concert.
     The budget is the total budget calculated.
     Include the campaign name, the campaign start date, the campaign end date, the campaign budget, the campaign demographics, the campaign venues, and the campaign media.
    Formulate the campaign structure to match the following example.
    Example campaign input data:
            "name": "{artist_name} Concert Tour {year}",
            "startDate": "2025-01-01",
            "endDate": "2025-12-31",
            "budget": 1280000,
            "monthlyPacing": 500,
            "dailyBudget": 10,
            "isAutoDailyPacing": false,
            "dailyPacing": 10,
            "type": "auction",
            "clickAttributionWindow": "30D",
            "viewAttributionWindow": "None",
            "clickAttributionScope": "sameSkuCategory",
            "viewAttributionScope": "sameSkuCategory",
        
    do not add any fields not in the example input data.
    output the new campaign from the Retail Media API.
    
  expected_output: >
    A JSON object with the campaign details.

create_lineitems:
  description: >
    Use the new campaign id to create line items for the campaign.
    For each concert, create a line item, with the following attributes:
      name: {artist_name} {year} - venue, city, country - concert date
      budget: budget amount for the concert
      startDate: 90 days before the concert date
      endDate: 1 day concert date
      campaignId: new campaign id
      Example input data for a new lineitem: {{
            "name": Taylor Swift 2025 - AccorHotels Arena, Paris, France - 2025-05-20,
            "campaignId": new campaign id,
            "status": "paused",
            "targetRetailerId": "1106",
            "budget": 50,
            "startDate": "2025-10-1",
            "endDate": "2025-12-31",
            "bidStrategy": "conversion",
            "targeBid": 1.0,
            }}
    when the linitems are created, fetch the linitems for the campaign  using the Retail Media API
    the results of the API are the expected output
    

  expected_output: >
    A JSON array of line items for the campaign.

summary:
  description: >
    Provide a summary of the campaign.
    Include:
    1. the account: name, contact, email using the {account_id}
    2. the new campaign: id, name, start date, end date, total budget.
    3. the new auction lineitems as a table with these columns: venue, concert date, seating capacity, budget amount, lineitem id, lineitem startDate and lineitem endDate
    4. A summary of the demographics for the artist.

  expected_output: >
    A summary in markdown format.
