accounts:
  description: >
    Fetch the accounts available to the account manager. 
    The results are paginated, so you may need to make multiple requests, start with pageIndex 0 and increment the pageIndex until you reach the last page.
    do not make more than the total number of pages.
  expected_output: >
    A list of accounts available to this user formatted as a table in Markdown. 
    Here is an example of the expected output:
    | Account ID | Name |	Type | Subtype | Countries | Currency | Parent Account Label | Time Zone | Company Name |

campaigns:
  description: >
    Use the {account_id} to get a list of campaigns.
    Do not hallucinate.
    Do not fabricate data.

  expected_output: >
    A list of campaign ids as a JSON array. Do not include the whold campaign object. Only the campaign Id.

research_demographics:
  description: >
    Use the {artist_name} to get the demographics for the artist.
    You will need to use the Web and Social media to obtain your data.

  expected_output: >
    A JSON object with the social media demographics for the artist.

find_concert_venues:
  description: >
    Use the {artist_name} to search the Web for the concerts and venues for {year}, indluding international venues.
    Include the seating capacity of each venue.
    Include the data of each concert.
    Do not hallucinate.
    Do not fabricate data.

  expected_output: >
    A JSON array of concerts, dates, venues and their searing capacity for the artist.

formulate_lineitem_budget:
  description: >

    Use the {digital_advertising_budget} to formulate the budget for the lineitems. 
    The sum of the lineitem budgets should equal the {digital_advertising_budget}.
    Express the budget in USD.
    Follow these steps:
    1. Use the venue budget calculator to calculate the budget for each venue, using the total bugdet and the seating capacity of the venue.
  expected_output: >
    A JSON object with the budget for the lineitems.

create_campaign_for_tour:
  description: >
    Create a ConcertCampaign for the  tour using the tool:'Campaign for concert tour'.
    The campaign should include all the concerts and venues for the tour.
    The campaign name is the {artist_name}, the {year}, the date of the first concert and the date of the last concert.
    The start date of the campaign should be 60 days before the first concert.
    The end date of the campaign should be the date of the last concert.
    startDate and endDate should be in the format "YYYY-MM-DD"
    The budget is the {digital_advertising_budget}.
    The monthlyPacing is calculated using the calculate monthly pacing tool.
    Include the campaign name, the campaign start date, the campaign end date, the campaign budget.

    Remember the new campaign as [newCampaign] 
    Example campaign fields data:
              "name": "{artist_name} Concert Tour {year}"
              "startDate": "2025-01-01"
              "endDate": "2025-12-31"
              "budget": {digital_advertising_budget}
              "monthlyPacing": 500
              "dailyBudget": 10
              "isAutoDailyPacing": fals
              "dailyPacing": 10
              "type": "auction"
              "clickAttributionWindow": "30D"
              "viewAttributionWindow": "None"
              "clickAttributionScope": "sameSkuCategory"
              "viewAttributionScope": "sameSkuCategory"
          
    do not add any fields not in the example campaign input data.
  expected_output: >
    the new ConcertCampaign.

create_campaign:
  description: >
    Use the NewCampaignTool to create a campaign with:
     
    The campaign name is the {artist_name}, the {year}, the date of the first concert and the date of the last concert.
    The start date of the campaign should be 60 days before the first concert.
    The end date of the campaign should be the date of the last concert.
    startDate and endDate should be in the format "YYYY-MM-DD"
    The budget is the {digital_advertising_budget}.
    The monthlyPacing is calculated using the calculate monthly pacing tool.
    Include the campaign name, the campaign start date, the campaign end date, the campaign budget.

    Remember the new campaign as [newCampaign] 
    Example campaign fields data:
              "name": "{artist_name} Concert Tour {year}",
              "startDate": "2025-01-01",
              "endDate": "2025-12-31",
              "budget": {digital_advertising_budget},
              "monthlyPacing": 500,
              "dailyBudget": 10,
              "isAutoDailyPacing": false,
              "dailyPacing": 10,
              "type": "auction",
              "clickAttributionWindow": "30D",
              "viewAttributionWindow": "None",
              "clickAttributionScope": "sameSkuCategory",
              "viewAttributionScope": "sameSkuCategory",
          
      do not add any fields not in the example campaign input data.

  expected_output: >
    [newCampaign] object as JSON.

create_lineitems:
  description: >
    Use the new campaign id to create line items for the campaign.
    For each concert, create a NewAcutionLineitemm using the NewAuctionLineitemTool, with the following attributes:
      name: {artist_name} {year} - venue, city, country - concert date
      budget: budget amount for the venue
      startDate: 90 days before the concert date
      endDate: 1 day before concert date
      startDate and endDate should be in the format "YYYY-MM-DD"
      campaignId: [newCampaign].id
      status: draft
      Example input data for a NewAuctionLineitem: 
            "name": Taylor Swift 2025 - AccorHotels Arena, Paris, France - 2025-05-20,
            "campaignId": "1234567890",
            "status": "draft",
            "targetRetailerId": "1106",
            "budget": 50,
            "startDate": "2025-10-1",
            "endDate": "2025-12-31",
            "bidStrategy": "conversion",
            "targeBid": 1.0,
      
    Fetch the  list of Lineitems for the [newCampaign] id using the AuctionLineitemsTool.
    Remember the list of Lineitems as [LineitemsList].
  expected_output: >
    A JSON array of AuctionLineitems.

summary:
  description: >
    Provide a summary of the campaign.
    Include:

    1. use [newCampaign] id, name, start date, end date, total budget.
    2. Format the [LineitemList] as a table with these columns: lineitem name, budget amount, lineitem id, lineitem startDate and lineitem endDate
    3. A summary of the demographics for the artist.

  expected_output: >
    A summary in markdown format.
