campaigns:
  description: >
    Use the account number of {account_id} to get a list of campaigns.

  expected_output: >
    A list of campaign ids for the account as a JSON array. Do not include the whold campaign object. Only the campaign Id.

ask_for_tour_name:
  description: >
    Ask the human for the artist_name.

  expected_output: >
    a string that is the artist_name.

research_demographics:
  description: >
    Use the artist_name to get the demographics for the artist.
    You will need to use the Web and Social media to obtain your data.

  expected_output: >
    A JSON object with the social media demographics for the artist.

find_concert_venues:
  description: >
    Use the artist_name to find the concerts and venues for 2025, indluding international venues.
    Include the seating capacity of each venue.
    Include the data of each concert.
    You will need to use the Web and Social media to obtain your data.

  expected_output: >
    A JSON array concerts, dates, venues and their searing capacity for the artist.
